config/routes.rb
Rails.application.routes.draw do

    resources :links

    get 'short-url/:short_url' => 'links#show_by_short_url', as: :show_by_short_url
    get 'show-modified-route/:short_url' => 'links#show_modified_route', as: :show_modified_route
end

app/models/link.rb
class Link < ActiveRecord::Base
    validates :long_url, presence: true, on: :create
    validates_format_of :long_url,
    with: /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#?&\/\/=]*)?\z/
    before_create :generate_random_slug

    def generate_random_slug
        chars_in_slug = 6
        alphabet_str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
        slug = []

        i = 0
        while i < chars_in_slug
            random_index = rand(0..61)
            slug[i] = alphabet_str[random_index]
            i += 1
        end
        
        self.short_url = slug.join()
        # self.save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_action :set_link, only: [:show]
    before_action :find_url, only: [:show_modified_route, :show_by_short_url]
    def index
        @links = Link.all
    end

    def new
        @link = Link.new
    end

    def create
        @link = Link.new(link_params)

        @link.save

        redirect_to show_modified_route_path(@link.short_url)
    end

    def show_by_short_url
        @link.click_count += 1
        @link.save

        long_url = @link.long_url
        if !long_url.start_with?("http://") && !long_url.start_with?("https://")
            long_url = "http://" + long_url
        end
        redirect_to long_url
    end

    def show_modified_route
        @link 

        @short_link = request.scheme + "://" + request.host + ":" + request.port.to_s + "/short-url/" + @link.short_url
    end

    private

    def find_url
        @link = Link.find_by_short_url(params[:short_url])
    end

    def set_link
        @link = Link.find(params[:id])
    end

    def link_params
        params.require(:link).permit(:long_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<h1>Most viewed links</h1>
<div>
    <% @links.each do |link| %>
        <p><%= link_to link_path(link.id) %></p>
    <% end %>
</div>

app/views/links/new.html.erb
<h1>Shorten your links</h1>


<%= form_for @link do |f| %>
  <p>
    <%= f.text_field :long_url, placeholder: "Enter the url you want to shorten"%>
    <%= f.submit %>
  </p>
<% end %>

app/views/links/show.html.erb
temp link page

app/views/links/show_modified_route.html.erb
<a href="<%= @short_link %>"><%= @short_link %></a>